RT: Rename BOT and pull new commits before pushing commit
nothing to commit, working tree clean
To https://github.com/geek0609/rom-tracker
 ! [rejected]        new-implementation -> new-implementation (fetch first)
error: failed to push some refs to 'https://github.com/geek0609/rom-tracker'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
Error: Process completed with exit code 1.

Signed-off-by: Ashwin.D.S <astroashwin@outlook.com>